version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    image: pynest-app
    container_name: pynest-app
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: eventbridgekh
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data # Define the volume pgdata
    networks:
      - app-network
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certs:/etc/nginx/certs
      depends_on:
        - web
      networks:
        - app-network    
      restart: unless-stopped

networks:
  app-network:

volumes:
  pgdata: # Define the volume pgdata